Boolean to lowercase
bitops-plugins/cloudformation pull request #10
Opened 2022-11-11 17:15 UTC by LeoDiazL

Changed variables to lowercase, and any other True/False to lowercase.
Some of them are not a must, but changed them to keep consistency.

2022-11-11 20:47 UTC, armab requested changes
Thanks for the changes @LeoDiazL and finding this 👍 
Having same formatting everywhere helps.

One question in the comment though.

2022-11-11 20:47 UTC, arm4b commented on bitops.schema.yaml
> +              required: true
This part is handled by the BitOps core and not by the plugin itself.

@PhillypHenning Do you think lowercase `true` in the bitops schema would be parsed properly by the BitOps core?

2022-11-11 20:47 UTC, arm4b commented on deploy.sh
> +if [[ "${CFN_TEMPLATE_VALIDATION}" == "true" ]] || [[ "${CFN_TEMPLATE_VALIDATION}" == "True" ]]; then
The code does the same as before.
What's the difference here?

2022-11-11 22:25 UTC, armab commented on bitops.schema.yaml
> +              required: true
Answering my own question.

Python's `yaml.parse` used in BitOps core should work ok on this, including `yes`, `no`.
Also interesting from the original YAML spec: https://stackoverflow.com/a/53648738

2022-11-14 12:34 UTC, LeoDiazL commented on deploy.sh
> +if [[ "${CFN_TEMPLATE_VALIDATION}" == "true" ]] || [[ "${CFN_TEMPLATE_VALIDATION}" == "True" ]]; then
Consistency. 
There are two more if's right after that, both of them validates lowercase values first.

2022-11-14 13:43 UTC, armab approved these changes

2022-11-14 13:45 UTC, merged